### STUDENTS REGISTER
POST http://localhost:6500/api/students/register
Content-Type: application/json

{
"name":"banana",
"email":"banana@banana.com",
"password":"Bananas24",
"schoolID":1234567
}

### TEACHERS REGISTER
POST http://localhost:6500/api/teachers/register
Content-Type: application/json

{
"name":"banana",
"email":"banana@apple.com",
"password":"Bananas24",
"schoolID":123456789,
"subject":"Mathematics",
"availability": [
      {
        "day": "Monday",
        "start": "23-03-2023",
        "end": "23-03-2023"
      }
    ]
}

### STUDENTS LOGIN
POST http://localhost:6500/api/students/login
Content-Type: application/json

{
"schoolID":1234567,
"password":"Bananas24"
}

### TEACHERS LOGIN
POST http://localhost:6500/api/teachers/login
Content-Type: application/json

{
    "schoolID":123456789,
    "password":"Bananas24"

}

### TEACHER CREATING AVAILABILITY TIME 
POST http://localhost:6500/api/appointments/6426d16e49698190b186cfdc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjZkMTZlNDk2OTgxOTBiMTg2Y2ZkYyIsImlhdCI6MTY4MDI2NTYxNSwiZXhwIjoxNjgwMjcyODE1fQ.LAmVG3RW9ArqptsgCYylmVzq53LKf4l-TFXosF-T0Rg

{
"date":"24-03-2023",
"time":["10:00","11:00","12:00"]
}

### GET ALL TEACHERS AVAILABILITIES
GET http://localhost:6500/api/appointments/allAvailability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjZkMTZlNDk2OTgxOTBiMTg2Y2ZkYyIsImlhdCI6MTY4MDI2NTYxNSwiZXhwIjoxNjgwMjcyODE1fQ.LAmVG3RW9ArqptsgCYylmVzq53LKf4l-TFXosF-T0Rg


