### STUDENTS REGISTER
POST http://localhost:6500/api/students/register
Content-Type: application/json

{
"name":"jon",
"email":"jon@jon.com",
"password":"Jon12345",
"schoolID":1234567
}

### TEACHERS REGISTER
POST http://localhost:6500/api/teachers/register
Content-Type: application/json

{
"name":"Ana",
"email":"ana@ana.com",
"password":"Ana12345",
"schoolID":123456789,
"subjects":"Mathematics"
}


### STUDENTS LOGIN
POST http://localhost:6500/api/students/login
Content-Type: application/json

{
"schoolID":1234567,
"password":"Jon12345"
}

### TEACHERS LOGIN
POST http://localhost:6500/api/teachers/login
Content-Type: application/json

{
    "schoolID":123456789,
    "password":"Ana12345"
}


### GET INFO OF A SPECIFIC STUDENT (BY ID)
GET http://localhost:6500/api/students/642ad3ac27349f4e9ca99544
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2FjMjczNDlmNGU5Y2E5OTU0NCIsImlhdCI6MTY4MDUyODU4NCwiZXhwIjoxNjgwNTM1Nzg0fQ.WTiceFB1B-u4ZGV3v9fmioVevtUTr_edc9dI8DdSNNc


### GET INFO OF A SPECIFIC TEACHER (BY ID)
GET http://localhost:6500/api/teachers/642ad3b027349f4e9ca99546
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2IwMjczNDlmNGU5Y2E5OTU0NiIsImlhdCI6MTY4MDUyODMyMiwiZXhwIjoxNjgwNTM1NTIyfQ.FWeYSzOGCWWv31uzQ8Ihc_p7MIV2QURN0DUvhsE6nUI


### TEACHER CREATING AVAILABILITY TIME 
POST http://localhost:6500/api/availabilities/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2IwMjczNDlmNGU5Y2E5OTU0NiIsImlhdCI6MTY4MDUyODMyMiwiZXhwIjoxNjgwNTM1NTIyfQ.FWeYSzOGCWWv31uzQ8Ihc_p7MIV2QURN0DUvhsE6nUI

{
"date":"27-03-2023",
"time":["09:00","10:00","12:00"]
}

### GET AVAILABILITY OF A SPECIFIC TEACHER (BY ID)
GET http://localhost:6500/api/availabilities/642ad3b027349f4e9ca99546
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2IwMjczNDlmNGU5Y2E5OTU0NiIsImlhdCI6MTY4MDUyODMyMiwiZXhwIjoxNjgwNTM1NTIyfQ.FWeYSzOGCWWv31uzQ8Ihc_p7MIV2QURN0DUvhsE6nUI

### STUDENT CREATING APPOINTMENT
POST http://localhost:6500/api/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2FjMjczNDlmNGU5Y2E5OTU0NCIsImlhdCI6MTY4MDUyODU4NCwiZXhwIjoxNjgwNTM1Nzg0fQ.WTiceFB1B-u4ZGV3v9fmioVevtUTr_edc9dI8DdSNNc

{
"teacher":"642ad3b027349f4e9ca99546",
"date":"27-03-2023",
"time":"12:00"
}

### GET APPOINTMENTS OF A SPECIFIC STUDENT (BY ID)
GET http://localhost:6500/api/appointments/642ad3ac27349f4e9ca99544
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MmFkM2FjMjczNDlmNGU5Y2E5OTU0NCIsImlhdCI6MTY4MDUyODU4NCwiZXhwIjoxNjgwNTM1Nzg0fQ.WTiceFB1B-u4ZGV3v9fmioVevtUTr_edc9dI8DdSNNc